version: "3"
services:

  angular-app:
    extends:
      file: node-apps.yml
      service: angular-app

  ts-app:
    extends:
      file: node-apps.yml
      service: ts-app


networks:
  default:
    external: true
    name: is-guides
