version: "3"
services:

  # Database
  wso2is-mysql-db-service:
    image: mysql:5.7
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wso2carbon
      MYSQL_PASSWORD: wso2carbon
    volumes:
      - ./configs/mysql/initdb:/docker-entrypoint-initdb.d
      - ./configs/mysql/my.cnf:/etc/mysql/my.cnf
      # Uncomment this line to save any IS changes to a volume
      - proxy-datavolume:/var/lib/mysql

  # Local Mailserver
  mailserver:
    image: mailhog/mailhog
    environment:
      VIRTUAL_HOST: mail.localhost,www.mail.localhost
      VIRTUAL_PORT: 8025
      SELF_SIGNED_HOST: mail.localhost
    ports:
      - "8025"
      - "1025"

  # Identity Server
  identity-server:
    image: docker.wso2.com/wso2is:5.11.0.0 #5.11.0.0 is the latest 5.11 version alias
    user: "root"
    ports:
      - "9763"
      - "9443"
    environment:
      VIRTUAL_PROTO: https
      VIRTUAL_HOST: is.localhost,www.is.localhost
      SELF_SIGNED_HOST: is.localhost
      VIRTUAL_PORT: 9443
    entrypoint:
      - "sh"
      - "-c"
      - |
          wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.1.0/wait-for | 
          sh -s -- wso2is-mysql-db-service:3306 --timeout=160 -- echo "db ready";

          # Pre-start commands:
          keytool -import -alias is -file $${WORKING_DIRECTORY}/wso2-artifact-volume/misc/certs/is.localhost.crt -keystore $${WSO2_SERVER_HOME}/repository/resources/security/client-truststore.jks -storepass wso2carbon -noprompt;

          echo "starting IS";
          $${WORKING_DIRECTORY}/docker-entrypoint.sh;
    volumes:
      - ./configs/identity-server:/home/wso2carbon/wso2-config-volume/repository/conf/
      - ./configs/security:/home/wso2carbon/wso2-config-volume/repository/resources/security/
      - ./components/dropins:/home/wso2carbon/wso2-artifact-volume/repository/components/dropins/
      - ./components/plugins:/home/wso2carbon/wso2-artifact-volume/repository/components/plugins/
      - ./components/misc:/home/wso2carbon/wso2-artifact-volume/misc
    depends_on:
      - wso2is-mysql-db-service
      - mailserver

volumes:
  # Persistant mysql data
  proxy-datavolume:
    driver: local

networks:
  default:
    external: true
    name: is-guides
